### ISSUE TITLE
Don't download empty strings

### ISSUE THREAD

**Issue by richardolsson** [zetkin/developer-utilities#25]
Currently, when translations are missing for a term, that term is still serialized as YAML after download, resulting in files like this:

```yaml
header:
    assignment: ""
    canvasser: ""
    progress: ""
    route: ""
item:
    stats:
        allocated: ""
        visited: ""
    unassigned: ""
```

Empty strings should not be saved.
